### ISSUE TITLE
Questions Regarding Data Pipeline

### ISSUE THREAD

**Issue by jonathoy** [covid19india/data#2]
Hi all,

My understanding is that the data flowing into this repository is about to slow down or stop entirely. I noticed that as of right now there are still periodic updates happening to the gh-pages branch with new data coming in.

With my limited understanding of your architecture as described [here](https://blog.covid19india.org/2020/09/04/architecture/), what I wanted to ask is if the process of putting data into Google Sheets completely manual and volunteer-led? Or is there also automation that is adding data into Sheets as well?

Thanks!

**Comment by siddhpant** [comment]
As far as I digged rn, a telegram bot is used which does OCR on state bulletin images. This is then verified by a volunteer, which approves it and the bot adds the data in the sheets.

Please refer the following:
 https://blog.covid19india.org/2021/08/24/operations/

https://github.com/covid19india/monitor-bot

https://github.com/bee-rickey/webScraper

https://github.com/covid19india/automation-bot

**Comment by bee-rickey** [comment]
Hi @jonathoy the bulletin is passed to a bot that parses it and provides a textual output. This is then pasted to a sheet manually. We did not do a full automation since image qualities decide how good the output of the bot is.
